### ISSUE TITLE
Make Bugfix Release

### ISSUE THREAD

**Issue by mhsdesign** [neos/neos-base-distribution#56]
This commit is currently not published when creating a new 7.3 project

https://github.com/neos/neos-base-distribution/commit/e98d14ddbb61cfa8f1aeced647bcc63677f2d585

**Comment by bwaidelich** [comment]
can you please describe what this issue is about :)

**Comment by mhsdesign** [comment]
The referenced commit (https://github.com/neos/neos-base-distribution/commit/e98d14ddbb61cfa8f1aeced647bcc63677f2d585) fixes https://github.com/neos/flow-development-collection/issues/2757
the commit was upmerged in all maintained branches. But only 8.0 was recently released.
So when one tries out a new 7.x project he will still encounter the issue: https://neos-project.slack.com/archives/C050C8FEK/p1651086195778329?thread_ts=1651064128.892389&cid=C050C8FEK

so we would need a 5.3 and 7.x release of this base-distribution i assume, so fresh projects created with composer create dont have this problem anymore.

**Comment by kdambekalns** [comment]
As of today the mentioned commit is included in releases for all branches:
<img width="452" alt="image" src="https://user-images.githubusercontent.com/95873/167658758-17826f87-2e92-4426-a642-d74b7619a609.png">

Can you provide clear instructions on how to reproduce the issue?

**Comment by kdambekalns** [comment]
Ok I get it. The commit is just wrong. Instead of what it did, it should have put the `allow-plugins` into `config`, like so:

```yaml
{
   "config": {
        "vendor-dir": "Packages/Libraries",
        "bin-dir": "bin",
        "allow-plugins": {
            "neos/composer-plugin": true
        }
    }
}
```
